name: Create release tag
on: workflow_dispatch

permissions:
  contents: write

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Run tests
        run: |
          tag=$(bash scripts/generate-release-tag)
          echo "generated-tag=$tag" >> $GITHUB_OUTPUT
        id: generate_tag
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = '${{ steps.generate_tag.outputs.generated-tag }}'

            const branch = '${{ github.ref_name }}'

            try {
              const resp = await github.rest.git.getRef({...context.repo, ref: `tags/${tag}`});
              return core.setFailed(`the tag ${tag} already exists on ${resp.data.object.type} ${resp.data.object.sha}`);
            } catch(err) {
              if(err.status !== 404){
                throw err;
              }
            }

            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            })
